'use client';
import {useEffect,useMemo,useState} from 'react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,Legend,PieChart,Pie,Cell,LineChart,Line,AreaChart,Area} from 'recharts';

const SHEET_ID='1KRfUfvw0JmbNBolkVDHyevutOv8nd3JYPgngT5xchFI';
const TABS=['Rough Data','For Hearing Entry','Centre Wise Report','Hearing Schedule Report','Date wise Report'];
const DATE_KEYS=['Date 1','Date 2','Date 3','Date 4','Date 5','Date 6','Date 7'];
const NOTICE_KEYS=['No. of Notices','No. of Notices (2)','No. of Notices (3)','No. of Notices (4)','No. of Notices (5)','No. of Notices (6)','No. of Notices (7)'];
const clean=v=>v==null?'':String(v).trim();
const num=v=>{const n=parseFloat(clean(v).replace(/,/g,''));return Number.isFinite(n)?n:0};
const norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
function val(row,wanted){const target=norm(wanted),keys=Object.keys(row);const exact=keys.find(x=>norm(x)===target);if(exact)return row[exact];const k=keys.find(x=>{const n=norm(x);return n.includes(target)||target.includes(n)});return k?row[k]:''}
function psNumber(row){const n=Number(clean(val(row,'New P.S. No.')).replace(/,/g,''));return Number.isInteger(n)&&n>=1&&n<=430?n:0}
function dateObj(s){const [d,m,y]=clean(s).split('-').map(Number);return new Date(y,m-1,d)}
function noticesForDate(row,date){if(!date||date==='All Dates')return 0;for(let i=0;i<DATE_KEYS.length;i++){if(clean(val(row,DATE_KEYS[i]))===date)return num(val(row,NOTICE_KEYS[i]))}return 0}
function centreForPS(ps){if((ps>=1&&ps<=50)||(ps>=55&&ps<=60)||(ps>=78&&ps<=79)||(ps>=91&&ps<=96))return 'GCSSS, SEC-3 DWARKA(P)';if((ps>=51&&ps<=54)||(ps>=61&&ps<=77)||(ps>=80&&ps<=90)||(ps>=97&&ps<=109)||(ps>=135&&ps<=145))return 'GCSSS, SEC-3 DWARKA(S)';if((ps>=110&&ps<=134)||(ps>=331&&ps<=341)||(ps>=343&&ps<=344)||(ps>=347&&ps<=349))return 'GCSSC SEC-22 DWARKA(R)';if((ps>=146&&ps<=234)||(ps>=276&&ps<=288))return 'VREC MATIALA';if((ps>=235&&ps<=275)||(ps>=289&&ps<=330))return 'MCD BOYS PRIMARY SCHOOL, QUTUB VIHAR';if(ps===342||(ps>=345&&ps<=346)||(ps>=350&&ps<=374))return 'GCSSS SEC 22 DWARKA(V)';if(ps>=375&&ps<=430)return 'GGSSS GHUMANHERA';return 'NOT MAPPED'}
async function getTab(tab){const r=await fetch(`/api/sheet?tab=${encodeURIComponent(tab)}`,{cache:'no-store'});const body=await r.json().catch(()=>({}));if(!r.ok)throw Error(body.error||`Unable to load ${tab}`);return body}
function Card({label,value,sub,accent='blue'}){return <div className={`card ${accent}`}><div className="card-top"><span className="card-label">{label}</span><span className="card-dot"/></div><div className="card-value">{value}</div><div className="card-sub">{sub}</div></div>}
function fmt(n){return Number(n||0).toLocaleString('en-IN')}

export default function Page(){
 const[data,setData]=useState({}),[error,setError]=useState(''),[loading,setLoading]=useState(true),[lastUpdated,setLastUpdated]=useState(null),[centre,setCentre]=useState('All Centres'),[date,setDate]=useState('All Dates'),[view,setView]=useState('overview');
 async function refresh(){setLoading(true);setError('');try{const r=await Promise.all(TABS.map(async t=>[t,await getTab(t)]));setData(Object.fromEntries(r));setLastUpdated(new Date())}catch(e){setError(e.message||'Unable to load Google Sheet')}finally{setLoading(false)}}
 useEffect(()=>{refresh();const id=setInterval(refresh,60000);return()=>clearInterval(id)},[]);

 const entry=data['For Hearing Entry']?.rows||[];
 const report=data['Centre Wise Report']?.rows||[];
 const currentPS=useMemo(()=>{const seen=new Set();return entry.filter(r=>{const n=psNumber(r);if(!n||seen.has(n))return false;seen.add(n);return true}).map(r=>({...r,'Hearing Centre':centreForPS(psNumber(r))}))},[entry]);
 const centreOptions=useMemo(()=>report.map(r=>clean(val(r,'Hearing Centre'))).filter(x=>x&&norm(x)!=='hearing centre').sort(),[report]);
 const filtered=useMemo(()=>currentPS.filter(r=>(centre==='All Centres'||val(r,'Hearing Centre')===centre)&&(date==='All Dates'||DATE_KEYS.some(k=>clean(val(r,k))===date))),[currentPS,centre,date]);
 const dateOptions=useMemo(()=>{const s=new Set();currentPS.forEach(r=>DATE_KEYS.forEach(k=>{const d=clean(val(r,k));if(d&&!/^date\s*\d+$/i.test(d))s.add(d)}));return [...s].sort((a,b)=>dateObj(a)-dateObj(b))},[currentPS]);
 const allTotals=useMemo(()=>({anomaly:currentPS.reduce((a,r)=>a+num(val(r,'Total Anamoly/Discripancy')),0),mapping:currentPS.reduce((a,r)=>a+num(val(r,'Total No Mapping')),0),grand:currentPS.reduce((a,r)=>a+num(val(r,'Grand Total')),0),balance:currentPS.reduce((a,r)=>a+num(val(r,'Balance No. of Notices')),0)}),[currentPS]);
 const totals=useMemo(()=>({anomaly:filtered.reduce((a,r)=>a+num(val(r,'Total Anamoly/Discripancy')),0),mapping:filtered.reduce((a,r)=>a+num(val(r,'Total No Mapping')),0),grand:date==='All Dates'?filtered.reduce((a,r)=>a+num(val(r,'Grand Total')),0):filtered.reduce((a,r)=>a+noticesForDate(r,date),0),balance:date==='All Dates'?filtered.reduce((a,r)=>a+num(val(r,'Balance No. of Notices')),0):Math.max(filtered.reduce((a,r)=>a+num(val(r,'Balance No. of Notices')),0)-filtered.reduce((a,r)=>a+noticesForDate(r,date),0),0)}),[filtered,date]);
 const centreChart=useMemo(()=>report.filter(r=>{const n=clean(val(r,'Hearing Centre'));return n&&norm(n)!=='hearing centre'&&(centre==='All Centres'||n===centre)}).map(r=>{const name=clean(val(r,'Hearing Centre'));const rows=currentPS.filter(x=>val(x,'Hearing Centre')===name);const scheduled=date==='All Dates'?num(val(r,'Total Notice Scheduled')):rows.reduce((a,x)=>a+noticesForDate(x,date),0);return{name,ps:num(val(r,'No. of P.S. under Hearing Centre')),anomaly:num(val(r,'Total Anamoly/ Discripancy')),mapping:num(val(r,'Total No Mapping')),grand:num(val(r,'Grand Total')),days:num(val(r,'Total Days Scheduled')),notices:scheduled,balance:num(val(r,'Balance Notices to be scheduled (No Map)'))}}),[report,currentPS,centre,date]);
 const scheduleChart=useMemo(()=>{const m={};currentPS.forEach(r=>{if(centre!=='All Centres'&&val(r,'Hearing Centre')!==centre)return;DATE_KEYS.forEach((k,i)=>{const d=clean(val(r,k));const n=num(val(r,NOTICE_KEYS[i]));if(d&&n)m[d]=(m[d]||0)+n})});return Object.entries(m).map(([date,scheduled])=>({date,scheduled})).sort((a,b)=>dateObj(a.date)-dateObj(b.date))},[currentPS,centre]);
 const topBLO=useMemo(()=>{const m={};filtered.forEach(r=>{const b=clean(val(r,'All BLO Name'));if(b)m[b]=(m[b]||0)+(date==='All Dates'?num(val(r,'Grand Total')):noticesForDate(r,date))});return Object.entries(m).map(([name,total])=>({name,total})).sort((a,b)=>b.total-a.total).slice(0,8)},[filtered,date]);
 const totalScheduled=useMemo(()=>scheduleChart.reduce((a,x)=>a+x.scheduled,0),[scheduleChart]);
 const nextDate=useMemo(()=>{const future=dateOptions.filter(d=>dateObj(d)>=new Date(new Date().setHours(0,0,0,0)));return future[0]||dateOptions[0]||'—'},[dateOptions]);
 const scheduledPct=allTotals.grand?Math.round((totalScheduled/allTotals.grand)*100):0;

 return <main>
 <header className="topbar"><div><div className="eyebrow">SIR 2026 • AC-34 MATIALA / DWARKA</div><h1>Hearing Operations Dashboard</h1><p>Live command view of hearing workload, scheduling, centres and BLO allocation.</p></div><div className="actions"><span className={`status ${loading?'loading':''}`}><i/> {loading?'Syncing':'Live'}</span><button onClick={refresh}>↻ Refresh</button><a href={`https://docs.google.com/spreadsheets/d/${SHEET_ID}/edit`} target="_blank" rel="noreferrer">Open Google Sheet ↗</a></div></header>
 {error&&<div className="error">Live sync failed: {error}</div>}
 <section className="filters"><div><label>Hearing Centre</label><select value={centre} onChange={e=>setCentre(e.target.value)}><option>All Centres</option>{centreOptions.map(x=><option key={x}>{x}</option>)}</select></div><div><label>Hearing Date</label><select value={date} onChange={e=>setDate(e.target.value)}><option>All Dates</option>{dateOptions.map(x=><option key={x}>{x}</option>)}</select></div><div className="filter-summary"><strong>{fmt(filtered.length)} P.S.</strong><span>{centre==='All Centres'?'All 7 hearing centres':centre}</span></div><div className="refresh-note"><span>● AUTO SYNC</span><br/>Every 60 seconds • {lastUpdated?`Last synced ${lastUpdated.toLocaleTimeString()}`:'Waiting for first sync'}</div></section>
 <nav className="tabs">{[['overview','Overview'],['centres','Centre Performance'],['schedule','Schedule'],['detail','P.S. / BLO Detail']].map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</nav>
 <section className="cards"><Card label="Current P.S." value={fmt(filtered.length)} sub={date==='All Dates'?'430 active P.S. in master view':`${date} • P.S. scheduled`} /><Card label="Anomaly / Discrepancy" value={fmt(totals.anomaly)} sub="Cases requiring identified verification" accent="amber"/><Card label="No Mapping" value={fmt(totals.mapping)} sub="Cases still requiring mapping" accent="orange"/><Card label={date==='All Dates'?'Grand Total':'Scheduled Notices'} value={fmt(totals.grand)} sub={date==='All Dates'?'Anomaly + No Mapping':'For selected hearing date'} accent="indigo"/><Card label="Balance Notices" value={fmt(totals.balance)} sub="Remaining hearing workload" accent="red"/><Card label="Hearing Centres" value={centreChart.length} sub={centre==='All Centres'?'7 active designated centres':centre} accent="green"/></section>

 {view==='overview'&&<>
 <section className="hero-grid"><div className="panel hero-panel"><div className="panel-head"><div><h2>Hearing Schedule</h2><p>Notices planned across all hearing dates</p></div><div className="hero-stat"><strong>{fmt(totalScheduled)}</strong><span>scheduled notices</span></div></div><ResponsiveContainer width="100%" height={285}><AreaChart data={scheduleChart} margin={{top:10,right:15,left:0,bottom:10}}><defs><linearGradient id="scheduleFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3157d5" stopOpacity=".24"/><stop offset="100%" stopColor="#3157d5" stopOpacity=".02"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip formatter={(v)=>[fmt(v),'Notices']}/><Area type="monotone" dataKey="scheduled" stroke="#3157d5" strokeWidth={3} fill="url(#scheduleFill)"/></AreaChart></ResponsiveContainer></div>
 <div className="panel next-panel"><div className="panel-head"><div><h2>Next Hearing Date</h2><p>Upcoming operational load</p></div><span className="mini-badge">LIVE</span></div><div className="next-date">{nextDate}</div><div className="next-list">{centreChart.slice().sort((a,b)=>b.notices-a.notices).slice(0,5).map(x=><div key={x.name}><span>{x.name}</span><strong>{fmt(x.notices)}</strong></div>)}</div></div></section>
 <section className="lower-grid"><div className="panel"><div className="panel-head"><div><h2>Centre Workload</h2><p>Scheduled notices by designated centre</p></div><span>{fmt(totalScheduled)} total</span></div><ResponsiveContainer width="100%" height={330}><BarChart data={centreChart} layout="vertical" margin={{top:5,right:25,left:10,bottom:5}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tick={{fontSize:11}}/><YAxis type="category" dataKey="name" width={180} tick={{fontSize:10}}/><Tooltip formatter={(v)=>[fmt(v),'Notices']}/><Bar dataKey="notices" fill="#3157d5" radius={[0,6,6,0]} barSize={25}/></BarChart></ResponsiveContainer></div>
 <div className="panel"><div className="panel-head"><div><h2>Workload Mix</h2><p>Current master workload</p></div><span>{scheduledPct}% scheduled</span></div><div className="donut"><ResponsiveContainer width="100%" height={245}><PieChart><Pie data={[{name:'Anomaly / Discrepancy',value:allTotals.anomaly},{name:'No Mapping',value:allTotals.mapping}]} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={62} outerRadius={92} paddingAngle={3}>{[0,1].map(i=><Cell key={i} fill={i===0?'#3157d5':'#a8b7e8'}/>)}</Pie><Tooltip formatter={(v)=>fmt(v)}/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{fmt(allTotals.grand)}</strong><span>Total cases</span></div></div><div className="legend-list"><div><i className="swatch blue"/>Anomaly <strong>{fmt(allTotals.anomaly)}</strong></div><div><i className="swatch light"/>No Mapping <strong>{fmt(allTotals.mapping)}</strong></div></div></div></section>
 <section className="panel"><div className="panel-head"><div><h2>Top BLO Workload</h2><p>Highest case volume in the selected view</p></div><span>Top 8</span></div><div className="rank">{topBLO.map((x,i)=><div className="rank-row" key={x.name}><b>{String(i+1).padStart(2,'0')}</b><span title={x.name}>{x.name.replace(/\s*\(.*?\)/g,'').replace(/\n/g,' ')}</span><strong>{fmt(x.total)}</strong></div>)}</div></section>
 </>}

 {view==='centres'&&<section className="panel"><div className="panel-head"><div><h2>Centre Performance</h2><p>Operational comparison of all designated hearing centres</p></div><span>{centreChart.length} centres</span></div><ResponsiveContainer width="100%" height={380}><BarChart data={centreChart} margin={{top:10,right:20,left:5,bottom:80}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" angle={-28} textAnchor="end" interval={0} height={100} tick={{fontSize:10}}/><YAxis tick={{fontSize:11}}/><Tooltip/><Legend/><Bar dataKey="ps" name="P.S." fill="#a8b7e8" radius={[5,5,0,0]}/><Bar dataKey="notices" name="Scheduled Notices" fill="#3157d5" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer><div className="table-wrap"><table><thead><tr><th>Hearing Centre</th><th>P.S.</th><th>Anomaly</th><th>No Mapping</th><th>Grand Total</th><th>Days</th><th>Scheduled</th><th>Balance</th></tr></thead><tbody>{centreChart.map(x=><tr key={x.name}><td><b>{x.name}</b></td><td>{fmt(x.ps)}</td><td>{fmt(x.anomaly)}</td><td>{fmt(x.mapping)}</td><td><b>{fmt(x.grand)}</b></td><td>{fmt(x.days)}</td><td><b>{fmt(x.notices)}</b></td><td>{fmt(x.balance)}</td></tr>)}</tbody></table></div></section>}

 {view==='schedule'&&<div className="schedule-grid"><section className="panel"><div className="panel-head"><div><h2>Daily Notice Schedule</h2><p>{centre==='All Centres'?'All hearing centres':centre}</p></div><span>{fmt(totalScheduled)} scheduled</span></div><ResponsiveContainer width="100%" height={390}><LineChart data={scheduleChart} margin={{top:10,right:20,left:0,bottom:20}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip formatter={(v)=>[fmt(v),'Notices']}/><Line type="monotone" dataKey="scheduled" stroke="#3157d5" strokeWidth={3} dot={{r:4}}/></LineChart></ResponsiveContainer></section><section className="panel"><div className="panel-head"><div><h2>Schedule Snapshot</h2><p>Date-wise planned notices</p></div></div><div className="schedule-list">{scheduleChart.map((r,i)=><div className={`schedule-row ${i===0?'first':''}`} key={r.date}><span><b>{r.date}</b><small>{i===0?'First scheduled date':''}</small></span><strong>{fmt(r.scheduled)}</strong></div>)}</div></section></div>}

 {view==='detail'&&<section className="panel"><div className="panel-head"><div><h2>P.S. / BLO Detail</h2><p>430 current polling-station records from For Hearing Entry</p></div><span>{fmt(filtered.length)} records</span></div><div className="table-wrap tall"><table><thead><tr><th>P.S.</th><th>Locality</th><th>BLO</th><th>Supervisor</th><th>Hearing Centre</th><th>Anomaly</th><th>No Mapping</th><th>Grand Total</th><th>Balance</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={`${psNumber(r)}-${i}`}><td><b>{psNumber(r)}</b></td><td>{clean(val(r,'LOCALITY'))}</td><td>{clean(val(r,'All BLO Name'))}</td><td>{clean(val(r,'Supervisor Name'))}</td><td>{clean(val(r,'Hearing Centre'))}</td><td>{fmt(num(val(r,'Total Anamoly/Discripancy')))}</td><td>{fmt(num(val(r,'Total No Mapping')))}</td><td><b>{fmt(num(val(r,'Grand Total')))}</b></td><td>{fmt(num(val(r,'Balance No. of Notices')))}</td></tr>)}</tbody></table></div></section>}
 <footer>Google Sheet • 5 source tabs • <b>{fmt(currentPS.length)} current P.S.</b> • Auto-sync every 60 seconds</footer></main>;
}
