'use client';
import {useEffect,useMemo,useState} from 'react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,Legend,PieChart,Pie,Cell,LineChart,Line} from 'recharts';
const SHEET_ID='1KRfUfvw0JmbNBolkVDHyevutOv8nd3JYPgngT5xchFI';
const TABS=['Rough Data','For Hearing Entry','Centre Wise Report','Hearing Schedule Report','Date wise Report'];
const DATE_KEYS=['Date 1','Date 2','Date 3','Date 4','Date 5','Date 6','Date 7'];
const clean=v=>v==null?'':String(v).trim();
const num=v=>{const n=parseFloat(clean(v).replace(/,/g,''));return Number.isFinite(n)?n:0};
const norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
function val(row,wanted){const target=norm(wanted),keys=Object.keys(row);const exact=keys.find(x=>norm(x)===target);if(exact)return row[exact];const k=keys.find(x=>{const n=norm(x);return n.includes(target)||target.includes(n)});return k?row[k]:''}
function psVal(row){const direct=val(row,'New P.S. No.');if(clean(direct))return clean(direct);const k=Object.keys(row).find(x=>{const n=norm(x);return /(^| )p s( |$)/.test(n)||n.includes('polling station')});return k?clean(row[k]):''}
async function getTab(tab){const r=await fetch(`/api/sheet?tab=${encodeURIComponent(tab)}`,{cache:'no-store'});const body=await r.json().catch(()=>({}));if(!r.ok)throw Error(body.error||`Unable to load ${tab}`);return body}
function Card({label,value,sub}){return <div className="card"><div className="card-label">{label}</div><div className="card-value">{value}</div><div className="card-sub">{sub}</div></div>}
export default function Page(){
 const[data,setData]=useState({}),[error,setError]=useState(''),[loading,setLoading]=useState(true),[lastUpdated,setLastUpdated]=useState(null),[centre,setCentre]=useState('All Centres'),[date,setDate]=useState('All Dates'),[view,setView]=useState('overview');
 async function refresh(){setLoading(true);setError('');try{const r=await Promise.all(TABS.map(async t=>[t,await getTab(t)]));setData(Object.fromEntries(r));setLastUpdated(new Date())}catch(e){setError(e.message||'Unable to load Google Sheet')}finally{setLoading(false)}}
 useEffect(()=>{refresh();const id=setInterval(refresh,60000);return()=>clearInterval(id)},[]);
 const entry=data['For Hearing Entry']?.rows||[],centres=data['Centre Wise Report']?.rows||[],schedule=data['Hearing Schedule Report']?.rows||[];
 // The sheet can contain repeated/old rows for the same P.S. We report one current record per NEW P.S. number.
 // If a P.S. appears more than once, the last occurrence is treated as the newest/current row.
 const validEntry=useMemo(()=>{const map=new Map();entry.forEach(r=>{const ps=psVal(r);if(ps)map.set(norm(ps),r)});return [...map.values()]},[entry]);
 const centreOptions=useMemo(()=>[...new Set(validEntry.map(r=>clean(val(r,'Hearing Centre'))).filter(Boolean))].sort(),[validEntry]);
 const dateOptions=useMemo(()=>[...new Set(validEntry.flatMap(r=>DATE_KEYS.map(k=>clean(val(r,k))).filter(v=>v&&!/^date\s*\d+$/i.test(v))))],[validEntry]);
 const filtered=useMemo(()=>validEntry.filter(r=>(centre==='All Centres'||clean(val(r,'Hearing Centre'))===centre)&&(date==='All Dates'||DATE_KEYS.some(k=>clean(val(r,k))===date))),[validEntry,centre,date]);
 const totals=useMemo(()=>({anomaly:filtered.reduce((a,r)=>a+num(val(r,'Total Anamoly/Discripancy')),0),mapping:filtered.reduce((a,r)=>a+num(val(r,'Total No Mapping')),0),grand:filtered.reduce((a,r)=>a+num(val(r,'Grand Total')),0),balance:filtered.reduce((a,r)=>a+num(val(r,'Balance No. of Notices')),0)}),[filtered]);
 const centreChart=useMemo(()=>centres.filter(r=>clean(val(r,'Hearing Centre'))&&norm(val(r,'Hearing Centre'))!=='hearing centre').map(r=>({name:clean(val(r,'Hearing Centre')),notices:num(val(r,'Total Notice Scheduled')),days:num(val(r,'Total Days Scheduled')),ps:num(val(r,'No. of P.S. under Hearing Centre'))})).sort((a,b)=>b.notices-a.notices),[centres]);
 const scheduleChart=useMemo(()=>schedule.filter(r=>clean(val(r,'Date'))&&num(val(r,'Total Hearing Scheduled'))>0).map(r=>({date:clean(val(r,'Date')),scheduled:num(val(r,'Total Hearing Scheduled'))})),[schedule]);
 const topBLO=useMemo(()=>{const m={};filtered.forEach(r=>{const b=clean(val(r,'All BLO Name'));if(b)m[b]=(m[b]||0)+num(val(r,'Grand Total'))});return Object.entries(m).map(([name,total])=>({name,total})).sort((a,b)=>b.total-a.total).slice(0,10)},[filtered]);
 return <main>
 <header className="topbar"><div><div className="eyebrow">ELECTORAL HEARING MANAGEMENT</div><h1>Hearing Schedule Dashboard</h1><p>Live operational view of workload, centres, hearing dates and BLO allocation.</p></div><div className="actions"><span className={`status ${loading?'loading':''}`}><i/> {loading?'Refreshing':'Live'}</span><button onClick={refresh}>↻ Refresh</button><a href={`https://docs.google.com/spreadsheets/d/${SHEET_ID}/edit`} target="_blank" rel="noreferrer">Open Sheet ↗</a></div></header>
 {error&&<div className="error">Could not load live data: {error}</div>}
 <section className="filters"><div><label>Hearing Centre</label><select value={centre} onChange={e=>setCentre(e.target.value)}><option>All Centres</option>{centreOptions.map(x=><option key={x}>{x}</option>)}</select></div><div><label>Hearing Date</label><select value={date} onChange={e=>setDate(e.target.value)}><option>All Dates</option>{dateOptions.map(x=><option key={x}>{x}</option>)}</select></div><div className="refresh-note">Auto refresh: every 60 seconds<br/>{lastUpdated?`Last synced ${lastUpdated.toLocaleTimeString()}`:'Waiting for first sync'}</div></section>
 <nav className="tabs">{[['overview','Overview'],['centres','Centre Performance'],['schedule','Schedule'],['detail','P.S. / BLO Detail']].map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</nav>
 <section className="cards"><Card label="P.S. Records" value={filtered.length.toLocaleString('en-IN')} sub={centre==='All Centres'?'All centres':centre}/><Card label="Anomaly / Discrepancy" value={totals.anomaly.toLocaleString('en-IN')} sub="Identified workload"/><Card label="No Mapping" value={totals.mapping.toLocaleString('en-IN')} sub="Mapping workload"/><Card label="Grand Total" value={totals.grand.toLocaleString('en-IN')} sub="Combined workload"/><Card label="Balance Notices" value={totals.balance.toLocaleString('en-IN')} sub="Current balance"/><Card label="Hearing Centres" value={centreChart.length} sub="Active centres"/></section>
 {view==='overview'&&<div className="grid"><section className="panel wide"><div className="panel-head"><h2>Scheduled Hearings by Centre</h2><span>Current sheet totals</span></div><ResponsiveContainer width="100%" height={340}><BarChart data={centreChart} margin={{top:10,right:20,left:10,bottom:90}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" angle={-35} textAnchor="end" interval={0} height={110}/><YAxis/><Tooltip/><Bar dataKey="notices" name="Notices Scheduled" fill="#3157d5" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></section><section className="panel"><div className="panel-head"><h2>Workload Mix</h2><span>Filtered P.S.</span></div><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={[{name:'Anomaly / Discrepancy',value:totals.anomaly},{name:'No Mapping',value:totals.mapping}]} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={95} label>{[0,1].map(i=><Cell key={i} fill={i===0?'#3157d5':'#8aa0e8'}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></section><section className="panel"><div className="panel-head"><h2>Top BLO Workload</h2><span>Grand total</span></div><div className="rank">{topBLO.map((x,i)=><div className="rank-row" key={x.name}><b>{i+1}</b><span>{x.name}</span><strong>{x.total.toLocaleString('en-IN')}</strong></div>)}</div></section></div>}
 {view==='centres'&&<section className="panel"><div className="panel-head"><h2>Centre Performance</h2><span>{centreChart.length} centres</span></div><ResponsiveContainer width="100%" height={380}><BarChart data={centreChart} margin={{top:10,right:20,left:10,bottom:90}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" angle={-35} textAnchor="end" interval={0} height={110}/><YAxis/><Tooltip/><Legend/><Bar dataKey="ps" name="P.S." fill="#8aa0e8"/><Bar dataKey="notices" name="Notices" fill="#3157d5"/></BarChart></ResponsiveContainer><div className="table-wrap"><table><thead><tr><th>Centre</th><th>P.S.</th><th>Days</th><th>Notices Scheduled</th></tr></thead><tbody>{centreChart.map(x=><tr key={x.name}><td>{x.name}</td><td>{x.ps.toLocaleString('en-IN')}</td><td>{x.days.toLocaleString('en-IN')}</td><td><b>{x.notices.toLocaleString('en-IN')}</b></td></tr>)}</tbody></table></div></section>}
 {view==='schedule'&&<div className="grid"><section className="panel wide"><div className="panel-head"><h2>Daily Hearing Schedule</h2><span>Scheduled dates</span></div><ResponsiveContainer width="100%" height={350}><LineChart data={scheduleChart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Line type="monotone" dataKey="scheduled" name="Hearings" stroke="#3157d5" strokeWidth={3}/></LineChart></ResponsiveContainer></section><section className="panel"><div className="panel-head"><h2>Schedule Snapshot</h2><span>Report tab</span></div><div className="schedule-list">{schedule.filter(r=>num(val(r,'Total Hearing Scheduled'))>0).map(r=><div className="schedule-row" key={clean(val(r,'Date'))}><span>{clean(val(r,'Date'))}</span><strong>{num(val(r,'Total Hearing Scheduled')).toLocaleString('en-IN')}</strong></div>)}</div></section></div>}
 {view==='detail'&&<section className="panel"><div className="panel-head"><h2>P.S. / BLO Detail</h2><span>{filtered.length} records</span></div><div className="table-wrap tall"><table><thead><tr><th>P.S.</th><th>Locality</th><th>BLO</th><th>Supervisor</th><th>Anomaly</th><th>Mapping</th><th>Grand Total</th><th>Balance Notices</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={i}><td><b>{psVal(r)}</b></td><td>{clean(val(r,'LOCALITY'))}</td><td>{clean(val(r,'All BLO Name'))}</td><td>{clean(val(r,'Supervisor Name'))}</td><td>{num(val(r,'Total Anamoly/Discripancy')).toLocaleString('en-IN')}</td><td>{num(val(r,'Total No Mapping')).toLocaleString('en-IN')}</td><td><b>{num(val(r,'Grand Total')).toLocaleString('en-IN')}</b></td><td>{num(val(r,'Balance No. of Notices')).toLocaleString('en-IN')}</td></tr>)}</tbody></table></div></section>}
 <footer>Source: Google Sheet • 5 source tabs • One current row per NEW P.S. • Auto-sync every 60 seconds</footer></main>;
}